### ISSUE TITLE
Funky Spectra Loading

### ISSUE THREAD

**Issue by Will-Cooper** [dr-rodriguez/AstrodbKit2#46]
Some spectra, e.g. of 2MASS J00325584-4405058, are causing the website to crash because specutils is running into a ```UnitConversionError``` when trying to load; this isn't being handled by astrodbkit2 (i.e. returning the spectrum as a string), hence the object crashing on the website (because the website is only handling a string instead of a ```Spectrum1D``` object). cc. @kelle

**Comment by Will-Cooper** [comment]
Okay right on closer inspection it's actually in SIMPLE-web, i.e. when converting to microns. For the aforementioned example object, it *is* loading correctly however it believes the unit to be in pixels; which of course cannot translate to microns... Question here then is *where* to handle these sorts of problems, cf. https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/225

**Comment by dr-rodriguez** [comment]
The related problem for the flux units is indeed a bug in the astrodbkit2 codebase: when reading spex data it grabs the flux units from the YUNITS header keyword and for these examples that is `ergss-1cm-2A-1` which is not a valid unit. The correct unit is `erg s-1cm-2A-1` and I've updated the code to catch these cases. The issue is with the FITS file itself, but I'll make a test in SIMPLE to identify incorrect DB entries as well.
